version: '2.0'

services:
  deluge:
     image: linuxserver/deluge:arm32v7-2.0.3-2201906121747ubuntu18.04.1-ls30
     volumes:
       - deluge_config:/config
       - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
     restart: unless-stopped
     network_mode: host
     privileged: true
     environment:
       PGID: 1000
       PUID: 1000
       TZ: Australia/Brisbane
       UMASK_SET: 000

  sonarr:
    image: linuxserver/sonarr:arm32v7-2.0.0.5322-ls25
    volumes:
      - sonarr_config:/config
      - ${MEDIA_LOCATION}/TV_Shows:/tv:shared
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000


  radarr:
    image: linuxserver/radarr:arm32v7-2.0.0.1399-ls13
    volumes:
      - radarr_config:/config
      - ${MEDIA_LOCATION}/Movies:/movies:shared
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Australia/Brisbane
      UMASK_SET: 000

  jackett:
    image: linuxserver/jackett:arm32v7-v0.11.487-ls30
    volumes:
      - jackett_config:/config
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Australia/Brisbane
      UMASK_SET: 000


volumes:
    deluge_config: {}
    sonarr_config: {}
    radarr_config: {}
    jackett_config: {}
