version: '3.2'

services:
  qbittorrent:
     image: linuxserver/qbittorrent:arm32v6-latest
     volumes:
       - ${MEDIA_LOCATION}/qbittorrent_config:/config
       - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
     restart: unless-stopped
     network_mode: host
     privileged: true
     environment:
       PGID: 1000
       PUID: 1000
       TZ: Australia/Brisbane
       UMASK_SET: 000
       WEBUI_PORT: 8081

  sonarr:
    image: linuxserver/sonarr:arm32v6-latest
    volumes:
      - ${MEDIA_LOCATION}/sonarr_config:/config
      - ${MEDIA_LOCATION}/TV_Shows:/tv:shared
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000


  radarr:
    image: linuxserver/radarr:arm32v6-latest
    volumes:
      - ${MEDIA_LOCATION}/radarr_config:/config
      - ${MEDIA_LOCATION}/Movies:/movies:shared
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Australia/Brisbane
      UMASK_SET: 000

  jackett:
    image: linuxserver/jackett:arm32v6-latest
    volumes:
      - ${MEDIA_LOCATION}/jackett_config:/config
      - ${MEDIA_LOCATION}/Torrent_Downloads:/downloads:shared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      PGID: 1000
      PUID: 1000
      TZ: Australia/Brisbane
      UMASK_SET: 000
